### ISSUE TITLE
请问dynamic modual应该怎么用呢？

### ISSUE THREAD

**Issue by lujun9972** [xuchunyang/emacs-osx-im-switcher#1]
能做个简单的介绍么？谢谢

**Comment by xuchunyang** [comment]
我也刚刚开始了解，基本没什么头绪。[syohex](https://github.com/syohex) 懂得蛮多的，他有篇 blog 是关于这个方面的：http://syohex.hatenablog.com/entry/2015/12/16/185458 ，还有几个与此相关的小项目（Linux下弹CD、跑 Ruby 和 curl 绑定）。

在 emacs 的 git repo 的下有个 modules 文件夹，里面有个测试用例，还有个可以用来创建模板的 Python 文件，我的这个 repo 最开始的代码就由它来的。

**Comment by xuchunyang** [comment]
这里有篇中文的：http://coldnew.github.io/blog/2015/01/03_emacsdynamic/

**Comment by lujun9972** [comment]
太感谢了,后面那篇文章写的很清晰,谢谢
